##############################################################
## General Configurations ##
##############################################################
homeassistant:
  name: Home
  latitude: 59.433776
  longitude: 18.323753
  elevation: 10
  unit_system: metric
  time_zone: Europe/Stockholm

frontend:
http:
  api_password: !secret http_password

updater:
discovery:
conversation:
history:
logbook:
sun:

tradfri:
  host: 192.168.0.127
  api_key: !secret tradfri_api_key

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

tellstick:
  signal_repetitions: 1

zwave:
  usb_path: /dev/ttyAMA0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config/

verisure:
  username: !secret verisure_username
  password: !secret verisure_password

media_player:
  - platform: cast

notify:
  - name: urban
    platform: pushbullet
    api_key: !secret pushbullet_api_key

#####################################################
#
# INCLUDES
#
#####################################################

###  Switches  ###
#  Switches are anything (hardware or software) that can turn
#  on or off.
switch: !include_dir_merge_list switches

logger: !include logger.yaml

group: !include group.yaml

automation: !include_dir_merge_list automation

# script: !include script.yaml
# scene: !include scene.yaml
# input_boolean: !include input_boolean.yaml
shell_command: !include shell_command.yaml

customize: !include customize.yaml

device_tracker: !include device_trackers.yaml

sensor: !include sensors.yaml

